[project]
name = "codeninja-cursor-cli"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.119.0",
    "pydantic>=2.12.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "uvicorn>=0.37.0",
    "websockets>=15.0.1",
]
